### ISSUE TITLE
Scoped packages are not working

### ISSUE THREAD

**Issue by ghost** [mozilla-b2g/npm-mirror#33]
Like the titles says, scoped packages which are supported since npm 2.7.0 are not working.

Example for such a package: https://github.com/node-xmpp/node-xmpp/tree/master/packages/jid

**Comment by heikkipora** [comment]
@markusdanek: This project seems dead so I did a replacement a while ago: https://github.com/heikkipora/registry-sync  (supports scoped packages as well)
