### ISSUE TITLE
instructions not clear

### ISSUE THREAD

**Issue by sonoman** [mozilla-b2g/npm-mirror#6]
Hey:

I'm trying to use this, but I'm not sure if I fully understand this part of the getting started:

npm install

DEBUG=npm-mirror:SyncManager bin/npm-mirror \
  --master http://registry.npmjs.org \
  --manifest /path/to/target/package.json \
  --hostname http://secret-npm-mirror.com \
  --root /where/we/put/packages/

Should I step on /usr/lib/node_modules/npm-mirror (where npm-mirror installed globally) and execute npm install with those DEBUG parameters ?
Can you help me understand that part ?
And after I do that, should I start a nginx web server for example, pointing to the root directory ?

**Comment by lightsofapollo** [comment]
So bin/npm-mirror is not super clear... that is the path inside of the repo but in reality you can reference the installed npm-mirror (if you have run npm install -g npm-mirror it is in your path so just `npm-mirror` should be fine)

> DEBUG parameters ?

DEBUG is in reference to https://github.com/visionmedia/debug and will spew lots of details about what is being synced. 

> And after I do that, should I start a nginx web server for example, pointing to the root directory ?

yes

**Comment by lambdabaa** [comment]
Does this help clarify things https://github.com/mozilla-b2g/npm-mirror/commit/926584d2630aa7c21a125cf9d6a33bc4937edaac ? Sorry for the confusion!
